name: brandie_flutter
description: A new Flutter project.

publish_to: "none"
version: 1.0.10

environment:
  flutter: 2.0.6
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_state_notifier: ^0.6.1
  provider: ^4.3.2+2
  state_notifier: ^0.6.0

  animations: any
  # cached_netword_image doesn't have support for web
  cached_network_image: ^2.5.1
  flutter_blurhash: ^0.5.0
  flutter_fluid_slider: ^1.0.3
  flutter_staggered_grid_view: ^0.3.2
  flutter_styled_toast: ^1.5.2+3
  font_awesome_flutter: ^8.11.0
  get_it: ^5.0.1
  google_fonts: ^1.1.1
  image: ^2.1.19
  like_button: ^1.0.4
  liquid_swipe: ^1.5.0
  modal_bottom_sheet: ^1.0.0+1
  page_transition: ^1.1.7+6
  preload_page_view: 0.1.4
  scroll_snap_list: ^0.6.0
  smooth_page_indicator: ^0.2.0
  transparent_image: ^1.0.0
  flutter_staggered_animations: "^1.0.0"
  url_launcher:
  js: ^0.6.3
  freezed_annotation: 0.12.0

  flat_icons_flutter: ^1.0.2
  percent_indicator: ^3.0.1
  fl_chart: ^0.36.1
  image_picker_web_redux: any
  form_validator: ^0.1.7
  shared_preferences_web: ^2.0.0
  path_provider: ^2.0.2
  url_strategy: ^0.2.0
  flare_flutter: ^3.0.2
  video_player: ^2.2.3

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  motion_widget: ^1.0.2
  pedantic: ^1.9.2
  test: ^1.15.7
  json_serializable:
  build_runner:
  freezed: 0.12.7
  analyzer: 0.40.6

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: Bellico
      fonts:
        - asset: assets/fonts/Bellico.ttf

    - family: Halimun
      fonts:
        - asset: assets/fonts/Halimun.ttf

    - family: QuiteMagical
      fonts:
        - asset: assets/fonts/QuiteMagical.ttf

    - family: Tomatoes
      fonts:
        - asset: assets/fonts/Tomatoes.ttf

    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand.ttf

    - family: Billabong
      fonts:
        - asset: assets/fonts/Billabong.ttf

    - family: GrandHotel
      fonts:
        - asset: assets/fonts/GrandHotel.ttf

    - family: BeautifulPeople
      fonts:
        - asset: assets/fonts/BeautifulPeople.ttf

    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf

    - family: FlatIcon
      fonts:
        - asset: assets/fonts/FlatIcon.ttf

    - family: Poppings-ExtraBold
      fonts:
        - asset: assets/fonts/Poppins-ExtraBold.ttf
        - asset: assets/fonts/Poppins-Black.ttf

    - family: Icofont
      fonts:
        - asset: assets/fonts/icofonts/icofont.ttf
